feat: get team schedule and populate teams
VandyHacks/witness pull request #428
Opened 2023-10-26 05:24 UTC by gabrield2731

added cli functionality to get a schedule for a team and to create test hackers and teams

2023-10-26 06:57 UTC, gabrield2731 commented
might be some weird merge conflict not sure though

2023-10-26 20:27 UTC, zineanteoh requested changes
thanks @gabrield2731 . have you tested your code on our dev database?

2023-10-26 20:27 UTC, zineanteoh commented on scripts/cli-util/get-team.ts
> +		console.log(`Zoom: ${schedule.zoom}`);
we no longer need zoom for schedule. ScheduleData model is really outdated. but we do need the table number (can be found in the team's document)

2023-10-26 20:27 UTC, zineanteoh commented on scripts/cli-util/populate-teams.ts
> +			devpost: 'test devpost',
generate a valid devpost link starting with https://devpost.com/{blablabla}

2023-10-27 04:06 UTC, zineanteoh commented on scripts/cli-util/delete-collection.ts
> +		await User.deleteMany({ userType: 'HACKER', email: { $ne: 'test-hacker@vandyhacks.dev' } });
```suggestion
		await User.deleteMany({ userType: 'HACKER', email: { $ne: 'testhacker@vandyhacks.dev' } });
```

2023-10-27 04:07 UTC, zineanteoh approved these changes
lgtm -- thanks @gabrield2731 !

2023-10-27 04:17 UTC, merged